//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludPlusAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promociones
    {
        public int PromocionID { get; set; }
        public int ProductoID { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
